on: push
name: Generate code
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18'
          registry-url: https://registry.npmjs.org
      - run: npx aws-sdk-js-codemod@latest -t v2-to-v3 example.ts
      - run: cat example.ts